-- Mashaal Rent a Car: database setup.
-- Run this once in Supabase: SQL Editor -> New query -> paste everything -> Run.
-- It is safe to run again; it does not delete any data.

-- ---------------------------------------------------------------- tables

create table if not exists public.cars (
  id           bigint generated by default as identity primary key,
  name         text        not null check (length(trim(name)) > 0),
  number       text        not null check (length(trim(number)) > 0),
  owner        text        not null default '',
  monthly_rent integer     not null check (monthly_rent >= 0),
  start_month  text        not null check (start_month ~ '^\d{4}-(0[1-9]|1[0-2])$'),
  active       boolean     not null default true,
  notes        text        not null default '',
  created_at   timestamptz not null default now()
);

-- A car number can be added only once (LEA-1234 and lea-1234 count as the same).
create unique index if not exists cars_number_unique on public.cars (upper(number));

create table if not exists public.payments (
  car_id     bigint      not null references public.cars (id) on delete cascade,
  month      text        not null check (month ~ '^\d{4}-(0[1-9]|1[0-2])$'),
  amount     integer     not null check (amount > 0),
  paid_on    date        not null,
  note       text        not null default '',
  created_at timestamptz not null default now(),
  primary key (car_id, month)
);

create index if not exists payments_month on public.payments (month);

-- A payment screenshot (or PDF). A rent entry can have more than one, for
-- example a partial payment made in two transfers.
create table if not exists public.receipts (
  id          bigint generated by default as identity primary key,
  car_id      bigint      not null,
  month       text        not null check (month ~ '^\d{4}-(0[1-9]|1[0-2])$'),
  path        text        not null unique,
  uploaded_at timestamptz not null default now(),
  foreign key (car_id, month) references public.payments (car_id, month) on delete cascade
);

create index if not exists receipts_car_month on public.receipts (car_id, month);

-- ---------------------------------------------------------------- security
-- Only people who are logged in can see or change anything.

alter table public.cars enable row level security;
alter table public.payments enable row level security;
alter table public.receipts enable row level security;

grant select, insert, update, delete on public.cars, public.payments, public.receipts to authenticated;
revoke all on public.cars, public.payments, public.receipts from anon;

drop policy if exists "Logged in users can do everything" on public.cars;
create policy "Logged in users can do everything" on public.cars
  for all to authenticated using (true) with check (true);

drop policy if exists "Logged in users can do everything" on public.payments;
create policy "Logged in users can do everything" on public.payments
  for all to authenticated using (true) with check (true);

drop policy if exists "Logged in users can do everything" on public.receipts;
create policy "Logged in users can do everything" on public.receipts
  for all to authenticated using (true) with check (true);

-- ---------------------------------------------------------------- payment screenshots (storage)
-- A private bucket for the files themselves. Only logged-in users can
-- upload, view or delete them; nothing here is public.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('receipts', 'receipts', false, 8388608, -- 8 MB
        array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif', 'application/pdf'])
on conflict (id) do update set
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Logged in users can manage receipt files" on storage.objects;
create policy "Logged in users can manage receipt files" on storage.objects
  for all to authenticated using (bucket_id = 'receipts') with check (bucket_id = 'receipts');

-- ---------------------------------------------------------------- restore backup
-- Replaces all cars and rent entries with the ones in a backup file, in one step:
-- if anything in the file is wrong, nothing is changed.

create or replace function public.restore_backup(backup jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce(auth.role(), '') <> 'authenticated' then
    raise exception 'Please log in';
  end if;
  if backup ->> 'app' is distinct from 'mashaal-rent'
     or jsonb_typeof(backup -> 'cars') is distinct from 'array'
     or jsonb_typeof(backup -> 'payments') is distinct from 'array' then
    raise exception 'This is not a Mashaal Rent backup file';
  end if;

  -- Backup files do not include screenshot images, so any already-uploaded
  -- receipt files are removed too (their database rows go with the payments,
  -- through the "on delete cascade" above).
  delete from storage.objects where bucket_id = 'receipts';
  delete from public.payments where true;
  delete from public.cars where true;

  insert into public.cars (id, name, number, owner, monthly_rent, start_month, active, notes, created_at)
  select id, name, number, coalesce(owner, ''), monthly_rent, start_month,
         coalesce(active, true), coalesce(notes, ''), coalesce(created_at, now())
  from jsonb_to_recordset(backup -> 'cars') as c(
    id bigint, name text, number text, owner text, monthly_rent integer,
    start_month text, active boolean, notes text, created_at timestamptz);

  insert into public.payments (car_id, month, amount, paid_on, note)
  select car_id, month, amount, paid_on, coalesce(note, '')
  from jsonb_to_recordset(backup -> 'payments') as p(
    car_id bigint, month text, amount integer, paid_on date, note text);

  -- New cars continue after the highest restored id.
  perform setval(pg_get_serial_sequence('public.cars', 'id'),
                 coalesce((select max(id) from public.cars), 0) + 1, false);
end;
$$;

revoke all on function public.restore_backup(jsonb) from public, anon;
grant execute on function public.restore_backup(jsonb) to authenticated;
